### ISSUE TITLE
change app.js to group it

### ISSUE THREAD

**Issue by asipser** [weblab-workshops/catbook-react#1]
- we need to style app.js with pretty block comments 
    - to indicate the staff middleware students shouldnt worry about (staff validator, etc)
    - to indicate the generic express middleware you use every time (body parser)
    - to indicate the route handling (route.get() routes)

**Comment by cory2067** [comment]
reorganized some stuff in the file to maybe make it a little more clear
don't know what you mean by "grouping"

**Comment by asipser** [comment]
looks much better. Small nit but would put one more comment over all the `const X = require('Y')` that this is just javascript syntax for importing the standard libraries that most webservers need. This way students won't think that they won't need it in their own code.

**Comment by asipser** [comment]
I also would add a header to app.js with something along the lines of 

```
/*
|--------------------------------------------------------------------------
| App.js -- The core of your server
|--------------------------------------------------------------------------
|
| This file defines how your server starts up. Think of it as the main() of your server.
| Lines X - Y imports modules/libraries needed by the server.
| Lines Y - Z defines personal settings (such as your personal database credentials)
| Lines Z - XX launches the express server, and hooks up the imported libraries to your server.
| Lines XX - YY finally define some routes for your server to serve clients your HTML files.
|
*/
```

**Comment by asipser** [comment]
on further thought im not positive if the specific line references are a good idea in case we change app.js in the future, but the general high level overview is something students would appreciate.

**Comment by asipser** [comment]
i added a small header, probably could be made better..
