### ISSUE TITLE
is NewPost a good design?

### ISSUE THREAD

**Issue by cory2067** [weblab-workshops/catbook-react#13]
just in terms of hierarchical component design, `NewPost` seems kind of suspect to me

```jsx
// currently
<NewPost comment=false />
<NewPost comment=true />
```

if we wanted to later add an input that isn't a comment or a story (like a chatbook message), then it's not obvious what we should do

```jsx
// gross
<NewPost type="comment" />
<NewPost type="story" />
<NewPost type="message" />
```

this design could end up being incoherent, with a long list of if statements to decide what logic to run based on which type. even with just 2 types it's kinda gross to me

i'm not sure what the conventions are for react component design, but how about something like this:
```jsx
<NewPost defaultText="New Comment" onSubmit={this.addComment} />
<NewPost defaultText="New Story" onSubmit={this.addStory} />
<NewPost defaultText="New Message" onSubmit={this.addMessage} />
```
this way, if you want to add a new input type, `NewPost` does not need to be modified, and provides a cleaner separation of logic

might be excessive, but then these could also become their own components
```jsx
class NewComment extends Component {
   render() {
     return (<NewPost defaultText="New Comment" onSubmit={this.addComment});
  }

  addComment(body) {
    post("/api/comment", {storyId: this.props.storyId, body});
  }
}
```

**Comment by MFarejowicz** [comment]
Sooo I think this is the correct way to do things, but it can be less intuitive when learning. I think the current setup is more beginner friendly, but obviously less extendable like you point out. Do we value something that's easier to learn or something that is "more correct"? I think we might honestly want the first...
