### ISSUE TITLE
would be a bit more verbose in Feed.js

### ISSUE THREAD

**Issue by asipser** [weblab-workshops/catbook-react#14]
This is one of the first actual components students will be looking at. Would rather suggest something like 

```

const hasStories = this.state.stories.length === 0;
if (!hasStories) {
 return <div> No stories </div>
}
else {
  return map(...)
}
```

Removes the ternary and the nesting of the code, which makes it easier for beginners to digest.

**Comment by a-lchen** [comment]
done
