### ISSUE TITLE
Week 1 Comments

### ISSUE THREAD

**Issue by MFarejowicz** [weblab-workshops/catbook-react#2]
- Should we clean up package.json? Seems to have some packages that are not used in week 1.
- Looks like the POST `story` and `comment` routes send empty objects just to send something and get the 200 status. Is this good practice (I am genuinely not sure)? Should we instead encourage always sending some useful string/data?
- `/api/*` 404 is nice =D
- Do we need props in `App.js`? Same with `NotFound.js`?
- Should we have a “loading” state in `Feed.js`? I think this is generally better practice than simply 2 states.
- Do we still need to use a form in the `NewPost.js` component? If the button `onClick` is already doing the POST request, I don’t know what a form adds.
- Do we want to handle users submitting a post with no text? What is best practice to handle this? I usually do this on the frontend.
- Card’s `getComments` seems inconsistent with Feed’s `getStories`. One literally just returns comments, and then chains into `setState`; the other directly calls `setState`. Do we have a preference on what is better? Does it matter?

**Comment by cory2067** [comment]
will clean up `package.json`

the http spec says it's up to the implementer what to return (if anything) in a POST response
either we should return nothing, or return the created resource (the latter could be useful if the frontend needs to know the `_id` of the created resource)

**Comment by nsinghal7** [comment]
+1 to `getComments` and `getStories` seeming inconsistent. I'd personally prefer directly calling `setState` since it keeps all the code associated with the fetch and handling that data in one place.

**Comment by asipser** [comment]
also, is it worth specifiying node version in package.json? It depends if we want students to build up their own package.json (a la `npm init`) or they will just take ours. If they just take ours it might be worth it to indicate a specific node version to minimize conflicts.

**Comment by asipser** [comment]
remove the form @a-lchen

**Comment by asipser** [comment]
@cory2067 add the frontend get/post and update Feed.js getStories to emulate Card.js with setting state.

**Comment by a-lchen** [comment]
form removed.

**Comment by asipser** [comment]
edit @cory2067 dont think you need to do frontend get/post @nsinghal7 will handle that, and i'll cover the feed.js getstories.
