### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by asipser** [weblab-workshops/catbook-react#32]
is ensureLoggedIn necessary for right now? not using it atm

should we use req.session.user instead of middleware?

where do we call /api/whoami in frontend, doing it in navbar seems wrong...

**Comment by cory2067** [comment]
maybe `/api/whoami` should be done in like `App.js` or something and it can pass the identity down to other components as props

last year, we used `ensureLoggedIn` on post story and post comment
that way, if somebody who isn't logged in tries to post something via the api, they get booted with a 401. it's probably worth using in catbook, so students know how to login-protect an api

**Comment by cory2067** [comment]
![image](https://user-images.githubusercontent.com/8433005/69129633-c8d75880-0a7c-11ea-8239-6237b581fd2f.png)
this should probably be changed so that `/api/login` returns your identity in the response body, so we don't need to make another call to whoami

**Comment by asipser** [comment]
todo: what cor said
