### ISSUE TITLE
wrapping fetch()

### ISSUE THREAD

**Issue by cory2067** [weblab-workshops/catbook-react#4]
the fetch API, while a lot better than `XMLHttpRequest` is still ass, and sending a simple POST request requires a lot of annoying repetitive code

how do we feel about having `get(endpoint, params)` and `post(endpoint, params)` utility functions like i had in `catbook-modern`: https://github.com/mit6148-workshops/catbook-modern/blob/master/public/js/api.js

**Comment by MFarejowicz** [comment]
+1

**Comment by asipser** [comment]
is okay to me, but we should document this file more heavily. eg what the code in format params doing (students will have never seem Object.keys() and map/filter/reduce chaining). There is probably a slightly more verbose but more clear way of writing this.

**Comment by cory2067** [comment]
i realize it also might be nice to add some cleaner error handling to this code

i remember last year, some people would send an invalid request to their server, and get some junk response that isn't JSON. this code would currently give some error message like "unexpected token in position 0" when it tries to do `res.json()` which is really cryptic

**Comment by asipser** [comment]
yes please LOL this would be super helpful. I think if this file is slightly more verbose and has better error handling then it's great to give to students.
