### ISSUE TITLE
API_ENDPOINT is a misnomer

### ISSUE THREAD

**Issue by cory2067** [weblab-workshops/catbook-react#40]
In workshop2 `utilities.js`, there's a constant `const API_ENDPOINT = "http://catbook-workshop2.herokuapp.com";`

I think this is an incorrect/misleading name, since the catbook website itself is not an API endpoint.
This is especially confusing when there's expressions like `API_ENDPOINT + endpoint`

Something like `BASE_URL` might be more accurate

**Comment by MFarejowicz** [comment]
donezo
