### ISSUE TITLE
consensus on removing config.js?

### ISSUE THREAD

**Issue by asipser** [weblab-workshops/catbook-react#6]
would rather have a top level config defined as `consts` in `app.js` and then transition to environment variables when the time comes. Fine by me if students end up pushing srvs to github (private repo, security is a meme anyways in this class).

could just be something like 
```
/*
|--------------------------------------------------------------------------
| Personal Server Configuration
|--------------------------------------------------------------------------
*/ 
const mongoConnectionURL = "blah blah blah"
...
```

**Comment by asipser** [comment]
hehexd @MFarejowicz

**Comment by MFarejowicz** [comment]
resolvesasda
