### ISSUE TITLE
consensus on changing scripts in package.json?

### ISSUE THREAD

**Issue by asipser** [weblab-workshops/catbook-react#7]
We definitely should change the `dev` script to be called `hotloader` so it aligns with the hotloader lingo we are teching.

we should remove the test script as its unnecessary

im hesitant if we should change remove `npm start` and make it `npm server` so students just learn `npm run hotloader` and `npm run server`. However i'm less sold on this, just a thought...

**Comment by cory2067** [comment]
would not change `npm start` because that's standard npm terminology
